---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Search for all running pods
      k8s_info:
        kind: Pod
        field_selectors:
          - status.phase=Running
