- hosts: 
    - localhost
  gather_facts: false
  tasks:
  - name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"
  - name: kubectl get secrets
    shell: kubectl get secrets
    register: kube_secrets
    
