
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wordpress2
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /wordpress2
        backend:
          serviceName: {{ .Values.service.name }} 
          servicePort: 80
