apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app}}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.app}}
    tier: {{ .Values.tier}}
  type: {{ .Values.service.type }}
